steps:
    - name: node
      entrypoint: npm
      args: ['install']
    - name: gcr.io/cloud-builders/gcloud
      entrypoint: 'bash'
      args: [ '-c', "gcloud secrets versions access latest --secret=frontend-protected --format='get(payload.data)' | tr '_-' '/+' | base64 -d > src/constants/protected.js" ]
    - name: node
      entrypoint: npm
      args: ['run', 'build']
    - name: 'gcr.io/cloud-builders/gcloud'
      args: [ 'compute', 'scp', '--recurse', '--zone=us-central1-a', '--project=igneous-future-259601', '/workspace/build', 'heyhatch@movieroulette-1:/tmp/frontend']
    - name: 'gcr.io/cloud-builders/gcloud'
      args: [ 'compute', 'ssh', 'heyhatch@movieroulette-1', '--command=rm -rf /home/heyhatch/frontend/*; mv /tmp/frontend/* /home/heyhatch/frontend/; rm -rf /tmp/frontend', '--zone=us-central1-a', '--project=igneous-future-259601']