export const ERROR_BACKEND_CONNECTION = "ERROR_BACKEND_CONNECTION";
export const ERROR_BACKEND_RESPONSE = "ERROR_BACKEND_RESPONSE";
export const ERROR_JSON = "ERROR_JSON";
export const ERROR_USER_NOT_LOGGED_IN = "ERROR_USER_NOT_LOGGED_IN";
export const ERROR_USER_NOT_FOUND = "ERROR_USER_NOT_FOUND";
